apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager
  - ./prometheus-operator
  - ./victoria-metrics
  - ./external-snapshotter
  - ./cosi
  - ./redis-operator
  - ./kubevirt-operator
  #- ./rook-ceph
  - ./grafana-operator
  #- ./kyverno
  #- ./metallb